server:
  port: 8760

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CrazySnailNO001/cloud-config
          #          https://github.com/CrazySnailNO001/cloud-config-server
          username: CrazySnailNO001
          password: xzh1003665947
          default-label: master #配置文件分支
          #          search-paths: cloud-config  #配置文件所在根目录
          search-paths: cloud-config-client  #配置文件所在根目录
#          search-paths: cloud-customer  #配置文件所在根目录
#          search-paths: '{application}'

eurekaServer:
  host: localhost  #注册中心的地址
  port: 8761       #注册中心服务端的端口号
#  user: martin     #注册中心安全校验用户名
#  password: 123456 #注册中心安全校验密码

eureka:
  server:
    max-time-for-replication: 30000
  client:
    register-with-eureka: true  #将此项目注册到Eureka服务
    service-url:
      defaultZone: http://localhost:8761/eureka/    #注册地址
    fetch-registry: true
    #          defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port}/eureka
#eureka:
#  instance:
#    prefer-ip-address: false
#    virtualHostName: ${spring.application.name}
#    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
#    homePageUrlPath: ${server.servlet.context-path}/actuator/
#    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
#    hostname: shiphub-asia-config.preprod.subsidia.org
#    non-secure-port: 8088
#    secure-port: 443
#    secure-port-enabled: true
#    instance-id: ${spring.application.name}:${server.port}
#    leaseRenewalIntervalInSeconds: 5
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: https://shiphub-asia-eureka-dev.preprod.subsidia.org/peer1/eureka,https://shiphub-asia-eureka-dev.preprod.subsidia.org/peer2/eureka